apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- metrics-service.yaml
- secret-template.yaml

labels:
- pairs:
    app.kubernetes.io/name: broadcaster
    app.kubernetes.io/part-of: todo-app
    app.kubernetes.io/version: 0.1.0
