apiVersion: v1
kind: Service
metadata:
  name: broadcaster-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: broadcaster
  ports:
    - name: http
      port: 8002
      protocol: TCP
      targetPort: 8002
