apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  labels:
    app: todo-backend
spec:
  selector:
    app: todo-backend
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
