apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- health-check-be.yaml
- health-check-fe.yaml
- httproute.yaml
- namespace.yaml
- secret-provider-class.yaml
- secret-provider-class-prod.yaml
- serviceaccount.yaml
