apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secret-provider-prod
  namespace: project
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "9b82dc92-8be2-4de4-90e4-e99eefb44e9f"
    keyvaultName: "kv-kubemooc-1754386572"
    tenantId: "b7cff52d-a4ec-4367-903c-5cf05c061aca"
    objects: |
      array:
        - |
          objectName: postgres-user-prod
          objectType: secret
        - |
          objectName: postgres-password-prod
          objectType: secret
  secretObjects:
  - secretName: postgres-secret-prod
    type: Opaque
    data:
    - objectName: postgres-user-prod
      key: USER
    - objectName: postgres-password-prod
      key: PASSWORD