apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: log-output-app:2.1
          imagePullPolicy: IfNotPresent
          env:
          - name: LOG_APP_APP_PORT
            value: "8000"
          - name: LOG_APP_LOG_LEVEL
            value: "INFO"
          - name: LOG_APP_PING_PONG_SERVICE_HOST
            value: "ping-pong-svc"  # This is the service name for the ping-pong app
          - name: LOG_APP_PING_PONG_SERVICE_PORT
            value: "2507"  # This is the port exposed by the ping-pong