apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cronjob
  namespace: project
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: todo-cron
              # WARNING: This image tag is automatically updated by CI/CD pipeline
              # DO NOT manually edit - tag gets replaced with commit SHA during deployment  
              image: kubemooc.azurecr.io/todo-app-cron:PLACEHOLDER-UPDATED-BY-CICD
              imagePullPolicy: IfNotPresent
              env:
                - name: TODO_BACKEND_URL
                  value: "http://todo-app-be-svc:2506"
                - name: LOG_LEVEL
                  value: "INFO"
                - name: WIKIPEDIA_RANDOM_URL
                  value: "https://en.wikipedia.org/wiki/Special:Random"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"