apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cronjob
  namespace: project
spec:
  # Runs every hour at :00
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: todo-cronjob
              image: kubemooc.azurecr.io/todo-cron:3.5
              imagePullPolicy: IfNotPresent
              env:
                - name: TODO_BACKEND_URL
                  value: "http://todo-app-be-svc:2506"
                - name: LOG_LEVEL
                  value: "INFO"
                - name: WIKIPEDIA_RANDOM_URL
                  value: "https://en.wikipedia.org/wiki/Special:Random"
