apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-be
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-be
  template:
    metadata:
      labels:
        app: todo-app-be
    spec:
      containers:
        - name: todo-backend
          # WARNING: This image tag is automatically updated by CI/CD pipeline
          # DO NOT manually edit - tag gets replaced with commit SHA during deployment
          image: kubemooc.azurecr.io/todo-app-be:PLACEHOLDER-UPDATED-BY-CICD
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8001"
            - name: LOG_LEVEL
              value: "INFO"
            - name: POSTGRES_HOST
              value: "postgres-svc"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "todoapp"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PASSWORD
          ports:
            - containerPort: 8001