apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-be
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-be
  template:
    metadata:
      labels:
        app: todo-app-be
    spec:
      containers:
        - name: todo-backend
          # WARNING: This image tag is automatically updated by CI/CD pipeline
          # DO NOT manually edit - tag gets replaced with commit SHA during deployment
          image: kubemooc.azurecr.io/todo-app-be:PLACEHOLDER-UPDATED-BY-CICD
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8001"
            - name: LOG_LEVEL
              value: "INFO"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POSTGRES_HOST
              value: "postgres-svc"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "todoapp"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PASSWORD
          ports:
            - containerPort: 8001
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /health
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 30
            successThreshold: 1
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          volumeMounts:
            - name: secrets-store-prod
              mountPath: "/mnt/secrets-store-prod"
              readOnly: true
      volumes:
        - name: secrets-store-prod
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "postgres-secret-provider-prod"