apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-cache-pvc
  namespace: project
spec:
  storageClassName: azurefile-csi  # Azure Files supports ReadWriteMany
  accessModes:
    - ReadWriteMany  # Allow multiple pods to share image cache
  resources:
    requests:
      storage: 1Gi