apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-cache-pvc
  namespace: project
spec:
  storageClassName: image-cache-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi