apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-cache-pvc
  namespace: project
spec:
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi