apiVersion: v1
kind: Service
metadata:
  name: todo-app-fe-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-app-fe
  ports:
    - port: 2507
      protocol: TCP
      targetPort: 8000