apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/broadcaster/

# Production webhook URL should be configured via CI/CD or external secret management
patches:
  - target:
      kind: Secret
      name: broadcaster-secret
    patch: |-
      - op: replace
        path: /stringData/WEBHOOK_URL
        value: "https://production-webhook.example.com/api/notify"
  - target:
      kind: Deployment
      name: broadcaster
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "INFO"
      - op: replace
        path: /spec/template/spec/containers/0/env/5/value
        value: "production"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"

# Override image tag for production (manual build/push workflow)
# TODO: Remove when integrated into CI/CD pipeline
images:
  - name: kubemooc.azurecr.io/broadcaster
    newTag: latest
