apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      initContainers:
        - name: fix-cache-permissions
          image: busybox
          command: ['sh', '-c', 'chmod 777 /images']
          volumeMounts:
            - name: image-cache-volume
              mountPath: /images
      volumes:
        - name: image-cache-volume
          persistentVolumeClaim:
            claimName: image-cache-pvc
      containers:
        - name: todo-app-server
          image: todo-app:1.13
          imagePullPolicy: IfNotPresent
          env:
            - name: IMAGE_CACHE_PATH
              value: "/images"
            - name: PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "INFO"
          volumeMounts:
            - name: image-cache-volume
              mountPath: /images
