apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: NodePort
  selector:
    app: todo-app     # This is the app as declared in the deployment.
  ports:
    - name: http
      nodePort: 30080   # Port available outside
      protocol: TCP
      port: 2507        # This is a port that is available to the cluster
      targetPort: 8000  # This is the target port (The actual app's port)