version: '3.8'

services:
  todo-app-be:
    image: todo-app-be:2.2
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo-app-be
    environment:
      - PORT=8001
      - LOG_LEVEL=INFO
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - todo-app-network

  todo-app-fe:
    image: todo-app-fe:2.2
    build:
      context: ./todo-app
      dockerfile: Dockerfile
    container_name: todo-app-fe
    environment:
      - PORT=8000
      - TODO_BACKEND_URL=http://todo-app-be:8001
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    volumes:
      - todo-images:/app/images
    depends_on:
      - todo-app-be
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - todo-app-network

# Define volumes for image caching
volumes:
  todo-images:
    driver: local

networks:
  # Custom network for service communication
  todo-app-network:
    driver: bridge
