apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: agc-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: nginx-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: agc-test
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>AGC Test Page</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background-color: #f0f8ff; }
            .container { max-width: 800px; margin: 0 auto; text-align: center; }
            h1 { color: #2c3e50; }
            .success { color: #27ae60; font-size: 18px; }
            .info { background-color: #ecf0f1; padding: 20px; border-radius: 5px; margin: 20px 0; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🎉 Azure Application Gateway for Containers Test</h1>
            <p class="success">✅ Success! Your AGC setup is working correctly.</p>
            <div class="info">
                <h3>Test Information</h3>
                <p><strong>Namespace:</strong> agc-test</p>
                <p><strong>Service:</strong> nginx-test</p>
                <p><strong>Gateway:</strong> Using Azure AGC (BYOD)</p>
                <p><strong>Timestamp:</strong> <span id="timestamp"></span></p>
            </div>
            <p>This page is served through Azure Application Gateway for Containers using the Gateway API.</p>
        </div>
        <script>
            document.getElementById('timestamp').textContent = new Date().toLocaleString();
        </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: agc-test
spec:
  selector:
    app: nginx-test
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
