apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Feature branch overlay - uses Azure Database for PostgreSQL instead of containerized PostgreSQL
# Usage: 
#   cd course_project/manifests/overlays/feature
#   kustomize edit set namespace feature-branch-name
#   kustomize edit set image [images...]
#   kustomize build . | kubectl apply -f -

# Include all base resources except PostgreSQL
  # Include all base resources except PostgreSQL
  # Note: Excluding ../../base/postgres/ - using Azure Database for PostgreSQL
  
  # Feature-specific SecretProviderClass for Azure Key Vault integration

  # Add resourcequota
resources:
- ../../base/shared/
- ../../base/todo-be/
- ../../base/todo-fe/
- ../../base/todo-cron/
- ../../base/nats/
- ../../base/broadcaster/
- secret-provider-class-feature.yaml
- resourcequota.yaml

# JSON patches for Azure PostgreSQL integration and AGC gateway migration
  # Replace the entire HTTPRoute to use AGC gateway with hostname-based routing

  # Add service account and Secret Provider Class volume to backend deployment
  # Note: This patch preserves health probes from base deployment

  # Ensure frontend health probes are properly configured
patches:
- patch: |-
    - op: replace
      path: /spec/parentRefs
      value:
        - name: agc-feature-gateway
          namespace: agc-shared
    - op: add
      path: /spec/hostnames
      value:
        - "BRANCH_NAME.23.98.101.23.nip.io"
    - op: replace
      path: /spec/rules
      value:
        - matches:
          - path:
              type: PathPrefix
              value: /be-health
          backendRefs:
            - name: todo-app-be-svc
              port: 2506
        - matches:
          - path:
              type: PathPrefix
              value: /docs
          backendRefs:
            - name: todo-app-be-svc
              port: 2506
        - matches:
          - path:
              type: PathPrefix
              value: /api
          backendRefs:
            - name: todo-app-be-svc
              port: 2506
        - matches:
          - path:
              type: PathPrefix
              value: /image
          backendRefs:
            - name: todo-app-fe-svc
              port: 2507
        - matches:
          - path:
              type: PathPrefix
              value: /todos
          backendRefs:
            - name: todo-app-fe-svc
              port: 2507
        - matches:
          - path:
              type: PathPrefix
              value: /
          backendRefs:
            - name: todo-app-fe-svc
              port: 2507
  target:
    kind: HTTPRoute
    name: todo-app
- patch: |-
    - op: add
      path: /spec/template/spec/serviceAccountName
      value: postgres-service-account
    - op: add
      path: /spec/template/spec/volumes
      value:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: postgres-secret-provider-feature
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value:
        - name: secrets-store
          mountPath: /mnt/secrets-store
          readOnly: true
    - op: replace
      path: /spec/template/spec/containers/0/env/3/value
      value: "kubemooc-postgres-feature.postgres.database.azure.com"
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: "BRANCH_NAME_DB"
  target:
    kind: Deployment
    name: todo-app-be
- path: nats-feature-patch.yaml

images:
- name: kubemooc.azurecr.io/todo-app-be
  newTag: latest
- name: kubemooc.azurecr.io/todo-app-fe
  newTag: latest
- name: kubemooc.azurecr.io/todo-app-cron
  newTag: latest
- name: kubemooc.azurecr.io/broadcaster
  newTag: latest

namespace: feature-BRANCH_NAME
