apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Feature branch overlay - used for deploying feature branches to separate namespaces
# Usage: 
#   cd course_project/manifests/overlays/feature
#   kustomize edit set namespace feature-branch-name
#   kustomize edit set image [images...]
#   kustomize build . | kubectl apply -f -

resources:
  - ../../base

# No patches needed - feature environments use same configuration as production
# Only namespace and images will be modified by CI/CD pipeline

images:
  - name: kubemooc.azurecr.io/todo-app-be
    newTag: latest
  - name: kubemooc.azurecr.io/todo-app-fe
    newTag: latest
