apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secret-provider-feature
  namespace: project  # This will be overridden by kustomize to feature namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "9b82dc92-8be2-4de4-90e4-e99eefb44e9f"
    keyvaultName: "kv-kubemooc-1754386572"
    tenantId: "b7cff52d-a4ec-4367-903c-5cf05c061aca"
    objects: |
      array:
        - |
          objectName: postgres-feature-user
          objectType: secret
        - |
          objectName: postgres-feature-password
          objectType: secret
  secretObjects:
  - secretName: postgres-secret
    type: Opaque
    data:
    - objectName: postgres-feature-user
      key: USER
    - objectName: postgres-feature-password
      key: PASSWORD
