apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Full stack kustomization - deploys all services together
# Usage: kubectl apply -k course_project/manifests/base/

  # Shared resources (namespace, secrets, routing, health checks)
  
  # Database service (must be deployed first for backend dependency)
  
  # Backend service (depends on postgres)
  
  # Frontend service (depends on backend)
  
  # Cron job service (depends on backend API)
  
  # Message bus (NATS) for async communication
  
  # Broadcaster service (depends on NATS for messaging)
resources:
- shared/
- postgres/
- todo-be/
- todo-fe/
- todo-cron/
- nats/
- broadcaster/
