apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Full stack kustomization - deploys all services together
# Usage: kubectl apply -k course_project/manifests/base/

resources:
  # Shared resources (namespace, secrets, routing, health checks)
  - shared/
  
  # Database service (must be deployed first for backend dependency)
  - postgres/
  
  # Backend service (depends on postgres)
  - todo-be/
  
  # Frontend service (depends on backend)
  - todo-fe/
  
  # Cron job service (depends on backend API)
  - todo-cron/
  
  # Message bus (NATS) for async communication
  - nats/
