apiVersion: ENC[AES256_GCM,data:UnE=,iv:AgmXmZcle3CsAAnK3oDdOdRrM+TLBj7U8MI7LznLF+Q=,tag:ydThpWe3bwFRldmMLj7QvQ==,type:str]
kind: ENC[AES256_GCM,data:6kQkME9W,iv:5x5zuInjfBneNucWcnQWR4UikxHNM5n947mcsfKUIck=,tag:RiDHPItERuJz7O0xuiVCfA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nqIMS9vuOX+1d7sbFerSPAEfdj9IFiPN6bPPYYXF,iv:BMcAMCDvQE913I91xwIwuSUlrTB/jQNwhuDDrt4VwYg=,tag:+ANv05JmAmvE9vi6ctWyMg==,type:str]
    namespace: ENC[AES256_GCM,data:PL77SZunXQNC,iv:TCmIhLDtLly7JEPKBQ5EUi3O07/P7BecUS7tnTMKmJk=,tag:vkeZJQn2kT6zB0oRQc5Mdg==,type:str]
type: ENC[AES256_GCM,data:BIoLzOBl,iv:wC/CBjs3rlv2yTNwIu6RF4tAC6eZ0hhnbWiLEkvxLN8=,tag:F+Tn4zezCgmBy0Agu5j4oA==,type:str]
data:
    #ENC[AES256_GCM,data:ijWJifob7XDg38FbpwzROE86qUkTJLoNe4cqoGanRQMGxk2lXMYWBEhftSmP,iv:cjRsg+7i389/gve6sqA/TfwsTXA/+3UjuQqAnxEu/8c=,tag:5SQ1TJID+iEGC2AoBnYgEw==,type:comment]
    client-id: ENC[AES256_GCM,data:wxBgUskfcuaMmCYNuNgT8WEePJYVWXj4AGeBNvzGXW6dVQbLKcDrfkUofLan9bva,iv:Z0O/mUMkXJk0PsAqHbKb9eTvodH8Fr5k2VWWCqEEArc=,tag:a8EOY97qfMNLUJtojnXwgg==,type:str]
    #ENC[AES256_GCM,data:QNqlYNtiWWLHzSwtVRi6eJZL1J7ivWaUb0I78aQH9EG6fln0akhDXTIsveJ+,iv:sTIKQSXhUP30zSvPlSkGRspkluKqD/FoCmmWUVOxGjw=,tag:j6u/Ukb+dRKyPiLkLEteAw==,type:comment]
    tenant-id: ENC[AES256_GCM,data:dPxotERAMs0xkSWaUxQFFeipY9/s9lgO8Q3vh2sEui7+QLnwUj7LX6ES3OuDfYHo,iv:UDRi2aMzHT/MfkG5CKpx6u5kbo6eyqJ9Dl405rsLFRk=,tag:2GJRGJmpYFTdlBNFfP6Ojg==,type:str]
sops:
    age:
        - recipient: age1m2gn2ehnzmfwpk48rez3r760258jdxm5nywturagrydyat6qdphqkkenjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYk42QytMaEpwS0tYU1RM
            Ym9oelNFWVBjc01xL09SUkZGK1JCVHI2NW13CmhqYTBBMFprcmx3VGF6QUxZTnhU
            WFdrcUZ3ZUMvZm5ZcWl1SG95dGZmdk0KLS0tIFhKdjl5UUdDQ0ZpMHVhVVljTHBQ
            S3Bua2ZMbUVQMmtHYXliT1pSQlFiVVUKHkZsg8wHCShn6S3gUUB+VDeK3p7D95Fc
            0ZR70CQTsAEbn/eyEuSTC7TLU/QXCflkK8frJqy9xykVAyaZ3fNR3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T01:22:28Z"
    mac: ENC[AES256_GCM,data:2wViNTFUA03sXWIQjB7rNfPU1CAYZ9lv6z36UmUHV3AW35BWpYVt4UfCYMe9vGBzuH8XLvia2rccWhAF9bE2rmpgaiqOf59ZGF6sl5dtoWpN9qADlhRH/vV2RloHnR6gJK0AUHNsffnZGbjz12VOGvbHOMfCJd7zyPVFL6kseg4=,iv:AJXjWy2bMSnmL7SqvtfJXC5udM10BN3FGDD7MEPzeVY=,tag:PgJfPFcUBGCV2quaISmHYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
