apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: exercises
  name: ping-pong-app
spec:
  replicas: 1
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: {}
        - setWeight: 50
        - pause: {}
        - setWeight: 75
        - pause: {}
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: kubemooc.azurecr.io/ping-pong-app:4.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: PING_PONG_APP_PORT
              value: "3000"
            - name: PING_PONG_LOG_LEVEL
              value: "INFO"
            - name: PING_PONG_DB_HOST
              value: "postgres-svc"
            - name: PING_PONG_DB_PORT
              value: "5432"
            - name: PING_PONG_DB_NAME
              value: "pingpong-db"
            - name: PING_PONG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: ping-pong-app-secret
                  key: DB_USER
            - name: PING_PONG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ping-pong-app-secret
                  key: DB_PASSWORD
