apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: ping-pong    # This is the app as declared in the deployment.
  ports:
    - name: app
      port: 2507        # This is the port that the service will expose.
      protocol: TCP
      targetPort: 3000  # This is the target port
    - name: auth-proxy
      port: 8080        # This exposes the sidecar port
      protocol: TCP
      targetPort: 8080  # This is the sidecar auth proxy port
