apiVersion: v1
kind: Pod
metadata:
  name: backup-test-pod
  namespace: project
spec:
  restartPolicy: Never
  containers:
    - name: backup-test
      image: kubemooc.azurecr.io/todo-cron:pg17-test
      imagePullPolicy: Always
      command: ["/usr/local/bin/backup_database.sh", "health"]
      env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: POSTGRES_HOST
          value: "postgres-svc"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "todoapp"
        - name: AZURE_STORAGE_ACCOUNT
          value: "kubemoocbackups"
        - name: AZURE_STORAGE_CONTAINER
          value: "database-backups"
        # Use the same credentials as the CronJob
        - name: AZURE_STORAGE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: account-name
        - name: AZURE_STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: account-key
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: PASSWORD
