apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
spec:
  type: NodePort
  selector:
    app: log-output     # This is the app as declared in the deployment.
  ports:
    - name: http
      nodePort: 30080   # Port available outside
      protocol: TCP
      port: 2506        # This is a port that is available to the cluster
      targetPort: 3000  # This is the target port