services:
  postgres:
    image: postgres:17
    container_name: todo_postgres_dev
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todoapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:17
    container_name: todo_postgres_test
    environment:
      POSTGRES_DB: todoapp_test
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data  # Use tmpfs for faster test database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todoapp_test"]
      interval: 2s
      timeout: 2s
      retries: 5

volumes:
  postgres_data:
