apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: nats
  app.kubernetes.io/component: messaging
  app.kubernetes.io/part-of: todo-app

commonAnnotations:
  app.kubernetes.io/version: "2.10.x"
