apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats
  labels:
    app.kubernetes.io/instance: nats
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.11.8
    helm.sh/chart: nats-9.0.28
automountServiceAccountToken: false