apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
  serviceName: nats
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nats
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7777"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: nats
          image: docker.io/bitnami/nats:2.10.7
          ports:
            - containerPort: 4222
            - containerPort: 7777
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
