apiVersion: v1
kind: ConfigMap
metadata:
  name: ama-metrics-settings-configmap
  namespace: kube-system
data:
  schema-version: v1
  config-version: ver1
  pod-annotation-based-scraping: |-
    podannotationnamespaceregex = "project"
