apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-serviceaccount
  namespace: default
  annotations:
    azure.workload.identity/client-id: "BACKUP_PRODUCTION_CLIENT_ID"  # Replace with actual client ID
  labels:
    app: database-backup
    component: backup-cron
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: default
  labels:
    app: database-backup
    component: backup-cron
data:
  POSTGRES_HOST: "postgres-svc.default.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "todoapp"
  AZURE_STORAGE_ACCOUNT: "kubemoocbackups"
  AZURE_STORAGE_CONTAINER: "database-backups"
  LOG_LEVEL: "INFO"
