name: Test Pipeline - Microservices

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'course_project/todo-app/**'
      - 'course_project/todo-backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'course_project/todo-app/**'
      - 'course_project/todo-backend/**'

jobs:
  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: course_project/todo-backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync --group dev
    
    - name: Run backend unit tests
      run: |
        uv run pytest tests/unit/ -v --tb=short
    
    - name: Run backend integration tests
      run: |
        uv run pytest tests/integration/ -v --tb=short
    
    - name: Generate backend coverage
      run: |
        uv run pytest tests/ --cov=src --cov-report=xml --cov-report=term-missing
    
    - name: Upload backend coverage
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage
        path: course_project/todo-backend/coverage.xml

  test-frontend:
    name: Frontend Tests  
    runs-on: ubuntu-latest
    needs: test-backend  # Frontend depends on backend contract
    defaults:
      run:
        working-directory: course_project/todo-app
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync --group dev
    
    - name: Run frontend unit tests (only existing features)
      run: |
        uv run pytest tests/unit/test_models.py -v --tb=short
        uv run pytest tests/unit/test_contracts.py -v --tb=short
        # TODO: Add test_todo_backend_client.py when contracts are finalized
    
    - name: Run frontend integration tests
      run: |
        uv run pytest tests/integration/ -v --tb=short
    
    - name: Generate frontend coverage
      run: |
        uv run pytest tests/unit/test_models.py tests/integration/ --cov=src --cov-report=xml --cov-report=term-missing
    
    - name: Upload frontend coverage
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage
        path: course_project/todo-app/coverage.xml

  test-microservice-integration:
    name: Service Integration Tests
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.13  
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build backend image
      run: |
        cd course_project/todo-backend
        docker build -t todo-backend:test .
    
    - name: Build frontend image  
      run: |
        cd course_project/todo-app
        docker build -t todo-app:test .
    
    - name: Test service communication
      run: |
        # Start backend
        docker run -d --name backend-test --network host -e PORT=8001 todo-backend:test
        
        # Wait for backend
        sleep 5
        
        # Test backend is responding
        curl -f http://localhost:8001/health || exit 1
        
        # Start frontend (pointing to backend)
        docker run -d --name frontend-test --network host -e PORT=8000 -e TODO_BACKEND_URL=http://localhost:8001 todo-app:test
        
        # Wait for frontend
        sleep 5
        
        # Test frontend health
        curl -f http://localhost:8000/health || exit 1
        
        # TODO: Add more integration tests when contracts are fixed
        
        # Cleanup
        docker stop backend-test frontend-test
        docker rm backend-test frontend-test
